spring.application.name=StudentManagementSystem

spring.datasource.username=root
spring.datasource.password=root


# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/studentmanagementsystem

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true